version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=native_image
      - MYSQL_ROOT_PASSWORD=local
      - TZ=Europe/London
    ports:
      - 3306:3306
